[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    br3ttb/PID@^1.2.1
    knolleary/PubSubClient@^2.8
lib_extra_dirs = dependencies

[env:test_firmware]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    adafruit/DHT sensor library@^1.4.6
lib_extra_dirs = dependencies
build_src_filter = +<*> -<hardware/main.cpp> +<hardware/test_firmware.cpp>

[env:test_firmware_with_relay]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    adafruit/DHT sensor library@^1.4.6
lib_extra_dirs = dependencies
build_src_filter = +<*> -<hardware/main.cpp> -<hardware/test_firmware.cpp> +<hardware/test_firmware_with_relay.cpp>